// src/routes/download/+page.svelte
<svelte:options runes={true} />

<script lang="ts">
  import type { PageProps } from './$types';
  import Button from '$components/ui/Button.svelte';
  import Card from '$components/ui/Card.svelte';
  import { Icon, ArrowTopRightOnSquare, ArrowDownTray, ComputerDesktop, DevicePhoneMobile } from 'svelte-hero-icons';
  import { downloadPlatforms } from '$lib/content/site';

  let { data }: PageProps = $props();
</script>

<section class="space-y-10 pb-12 pt-6 md:space-y-12 md:pt-10">
  <div class="hero-panel px-6 py-8 md:px-8 md:py-10 xl:px-12">
    <div class="grid gap-8 lg:grid-cols-[1.15fr_0.85fr] lg:items-end">
      <div class="space-y-5">
        <div class="eyebrow-badge">Downloads</div>
        <h1 class="section-title max-w-4xl">Choose the BetterSEQTA experience that fits how you work.</h1>
        <p class="hero-kicker">
          Install the extension for the quickest upgrade, or download DesQTA for the full desktop experience with a wider layout and room for more powerful workflows.
        </p>
        <div class="flex flex-wrap gap-3">
          <Button href="#desqta-downloads">
            <Icon class="h-5 w-5" src={ArrowDownTray} />
            Desktop downloads
          </Button>
          <Button href="/comparison" variant="ghost">
            Compare editions
            <Icon class="h-5 w-5" src={ArrowTopRightOnSquare} />
          </Button>
        </div>
      </div>

      <div class="grid gap-4 sm:grid-cols-2">
        <div class="metric-card">
          <div class="text-xs font-semibold uppercase tracking-[0.18em] text-soft">Desktop release</div>
          <div class="mt-3 text-2xl font-semibold text-white">{data.release?.tag_name ?? 'Latest build'}</div>
          <div class="mt-1 text-sm text-muted">Current DesQTA version across supported platforms.</div>
        </div>
        <div class="metric-card">
          <div class="text-xs font-semibold uppercase tracking-[0.18em] text-soft">Install choices</div>
          <div class="mt-3 text-2xl font-semibold text-white">Browser + desktop</div>
          <div class="mt-1 text-sm text-muted">Chrome, Edge, Firefox, Windows, macOS, Android, and more.</div>
        </div>
      </div>
    </div>
  </div>

  <section class="space-y-6">
    <div class="max-w-3xl space-y-3">
      <div class="section-subtitle">Extension install</div>
      <h2 class="text-3xl font-semibold tracking-tight text-white md:text-4xl">Get BetterSEQTA+ in your browser in a few clicks.</h2>
      <p class="text-lg leading-8 text-muted">
        Fastest way to improve SEQTA Learn if you already live in your browser day to day.
      </p>
    </div>

    <div class="grid gap-5 md:grid-cols-3">
      <Card className="space-y-5 p-6 md:p-7">
        <div class="space-y-2">
          <div class="section-subtitle">Chrome</div>
          <h3 class="text-2xl font-semibold text-white">Chrome Web Store</h3>
          <p class="text-muted">Install the main browser build for Chrome and Chromium-based browsers.</p>
        </div>
        <Button href="https://chromewebstore.google.com/detail/betterseqta+/afdgaoaclhkhemfkkkonemoapeinchel">Add to Chrome</Button>
      </Card>

      <Card className="space-y-5 p-6 md:p-7">
        <div class="space-y-2">
          <div class="section-subtitle">Edge</div>
          <h3 class="text-2xl font-semibold text-white">Microsoft Edge</h3>
          <p class="text-muted">Same fast install path for Edge users who want the browser-first experience.</p>
        </div>
        <Button href="https://chromewebstore.google.com/detail/betterseqta+/afdgaoaclhkhemfkkkonemoapeinchel">Add to Edge</Button>
      </Card>

      <Card className="space-y-5 p-6 md:p-7">
        <div class="space-y-2">
          <div class="section-subtitle">Firefox</div>
          <h3 class="text-2xl font-semibold text-white">Mozilla Add-ons</h3>
          <p class="text-muted">Grab the Firefox version if you want BetterSEQTA+ without switching browsers.</p>
        </div>
        <Button href="https://addons.mozilla.org/en-US/firefox/addon/betterseqta-plus/">Add to Firefox</Button>
      </Card>
    </div>
  </section>

  <section class="space-y-6" id="desqta-downloads">
    <div class="max-w-3xl space-y-3">
      <div class="section-subtitle">Desktop and mobile</div>
      <h2 class="text-3xl font-semibold tracking-tight text-white md:text-4xl">Download DesQTA for the devices you already use.</h2>
      <p class="text-lg leading-8 text-muted">
        The full BetterSEQTA desktop experience with platform-native installs and room for a much broader UI.
      </p>
    </div>

    <div class="grid gap-5 lg:grid-cols-2 2xl:grid-cols-4">
      {#each downloadPlatforms as platform}
        <Card className="flex h-full flex-col gap-5 p-6 md:p-7">
          <div class="flex items-start justify-between gap-4">
            <div class="space-y-2">
              <div class="section-subtitle">{platform.label}</div>
              <h3 class="text-2xl font-semibold text-white">{platform.label}</h3>
            </div>
            <div class="rounded-2xl border border-white/8 bg-white/5 p-3 text-white">
              {#if platform.key === 'android'}
                <Icon class="h-6 w-6" src={DevicePhoneMobile} />
              {:else}
                <Icon class="h-6 w-6" src={ComputerDesktop} />
              {/if}
            </div>
          </div>

          <p class="text-base leading-7 text-muted">{platform.blurb}</p>

          {#if data.release?.tag_name}
            <div class="rounded-2xl border border-white/8 bg-white/3 px-4 py-3 text-sm text-soft">
              Latest release: <span class="font-semibold text-white">{data.release.tag_name}</span>
            </div>
          {/if}

          <div class="mt-auto space-y-3">
            {#if platform.key === 'windows'}
              <Button href={data.links.exe || '#'}>{platform.primary}</Button>
              <Button href={data.links.msi || '#'} variant="ghost">Download MSI</Button>
            {:else if platform.key === 'macos'}
              <Button href={data.links.dmg || '#'}>{platform.primary}</Button>
            {:else if platform.key === 'android'}
              <Button href={data.links.apk || '#'}>{platform.primary}</Button>
            {:else}
              <Button variant="ghost" className="w-full justify-center opacity-70">{platform.primary}</Button>
            {/if}
          </div>
        </Card>
      {/each}
    </div>
  </section>
</section>

// pages/download.vue
<template>
  <div class="relative isolate overflow-hidden">
    <div class="mx-auto max-w-7xl px-6 py-24 sm:py-32 lg:px-8 animate-fade-in">
      <div class="mx-auto max-w-2xl text-center">
        <h2 class="text-base font-semibold leading-7 text-zinc-400 animate-slide-down">Installation</h2>
        <p class="mt-2 text-3xl font-bold tracking-tight text-white sm:text-4xl animate-slide-down delay-100">
          Add BetterSEQTA Plus to your browser
        </p>
        <p class="mt-6 text-lg leading-8 text-zinc-300 animate-fade-in delay-200">
          Transform your SEQTA Learn experience with our powerful browser extension.
        </p>
      </div>

      <div class="mx-auto mt-16 max-w-2xl sm:mt-20 lg:mt-24 lg:max-w-none grid grid-cols-1 lg:grid-cols-3 gap-8">
        <!-- Chrome Card -->
        <div class="backdrop-blur-lg bg-white/5 border border-white/10 rounded-2xl shadow-xl p-8 flex flex-col items-start transition-transform duration-300 hover:-translate-y-2 hover:shadow-2xl animate-fade-in">
          <dt class="flex items-center gap-x-3 text-base font-semibold leading-7 text-white">
            <svg class="h-7 w-7 flex-none text-zinc-400 transition-transform duration-300 group-hover:scale-110" viewBox="0 0 24 24" fill="currentColor">
              <path d="M12 0C8.21 0 5 2.54 5 5.68c0 2.12 1.21 3.97 3.03 5.08C5.99 12.62 4 15.23 4 18.32c0 3.31 2.69 6 6 6s6-2.69 6-6c0-3.09-1.99-5.7-5.03-6.56 1.82-1.11 3.03-2.96 3.03-5.08C19 2.54 15.79 0 12 0zm0 2c2.21 0 4 1.79 4 4s-1.79 4-4 4-4-1.79-4-4 1.79-4 4-4zm0 14c-2.21 0-4 1.79-4 4s1.79 4 4 4 4-1.79 4-4-1.79-4-4-4z"/>
            </svg>
            <span class="ml-2">Chrome</span>
          </dt>
          <dd class="mt-4 flex flex-auto flex-col text-base leading-7 text-zinc-300">
            <p class="flex-auto">Install BetterSEQTA Plus on Chrome for the best experience.</p>
            <p class="mt-6">
              <a href="https://chromewebstore.google.com/detail/betterseqta+/afdgaoaclhkhemfkkkonemoapeinchel" class="text-sm font-semibold leading-6 text-zinc-400 transition-colors duration-200 hover:text-zinc-300 focus:text-zinc-200">
                Add to Chrome <span aria-hidden="true">→</span>
              </a>
            </p>
          </dd>
        </div>
        <!-- Edge Card -->
        <div class="backdrop-blur-lg bg-white/5 border border-white/10 rounded-2xl shadow-xl p-8 flex flex-col items-start transition-transform duration-300 hover:-translate-y-2 hover:shadow-2xl animate-fade-in delay-100">
          <dt class="flex items-center gap-x-3 text-base font-semibold leading-7 text-white">
            <svg class="h-7 w-7 flex-none text-zinc-400 transition-transform duration-300 group-hover:scale-110" viewBox="0 0 24 24" fill="currentColor">
              <path d="M12 0C8.21 0 5 2.54 5 5.68c0 2.12 1.21 3.97 3.03 5.08C5.99 12.62 4 15.23 4 18.32c0 3.31 2.69 6 6 6s6-2.69 6-6c0-3.09-1.99-5.7-5.03-6.56 1.82-1.11 3.03-2.96 3.03-5.08C19 2.54 15.79 0 12 0zm0 2c2.21 0 4 1.79 4 4s-1.79 4-4 4-4-1.79-4-4 1.79-4 4-4zm0 14c-2.21 0-4 1.79-4 4s1.79 4 4 4 4-1.79 4-4-1.79-4-4-4z"/>
            </svg>
            <span class="ml-2">Edge</span>
          </dt>
          <dd class="mt-4 flex flex-auto flex-col text-base leading-7 text-zinc-300">
            <p class="flex-auto">Install BetterSEQTA Plus on Microsoft Edge.</p>
            <p class="mt-6">
              <a href="https://chromewebstore.google.com/detail/betterseqta+/afdgaoaclhkhemfkkkonemoapeinchel" class="text-sm font-semibold leading-6 text-zinc-400 transition-colors duration-200 hover:text-zinc-300 focus:text-zinc-200">
                Add to Edge <span aria-hidden="true">→</span>
              </a>
            </p>
          </dd>
        </div>
        <!-- Firefox Card -->
        <div class="backdrop-blur-lg bg-white/5 border border-white/10 rounded-2xl shadow-xl p-8 flex flex-col items-start transition-transform duration-300 hover:-translate-y-2 hover:shadow-2xl animate-fade-in delay-200">
          <dt class="flex items-center gap-x-3 text-base font-semibold leading-7 text-white">
            <svg class="h-7 w-7 flex-none text-zinc-400 transition-transform duration-300 group-hover:scale-110" viewBox="0 0 24 24" fill="currentColor">
              <path d="M12 0C8.21 0 5 2.54 5 5.68c0 2.12 1.21 3.97 3.03 5.08C5.99 12.62 4 15.23 4 18.32c0 3.31 2.69 6 6 6s6-2.69 6-6c0-3.09-1.99-5.7-5.03-6.56 1.82-1.11 3.03-2.96 3.03-5.08C19 2.54 15.79 0 12 0zm0 2c2.21 0 4 1.79 4 4s-1.79 4-4 4-4-1.79-4-4 1.79-4 4-4zm0 14c-2.21 0-4 1.79-4 4s1.79 4 4 4 4-1.79 4-4-1.79-4-4-4z"/>
            </svg>
            <span class="ml-2">Firefox</span>
          </dt>
          <dd class="mt-4 flex flex-auto flex-col text-base leading-7 text-zinc-300">
            <p class="flex-auto">Install BetterSEQTA Plus on Firefox.</p>
            <p class="mt-6">
              <a href="https://addons.mozilla.org/en-US/firefox/addon/betterseqta-plus/" class="text-sm font-semibold leading-6 text-zinc-400 transition-colors duration-200 hover:text-zinc-300 focus:text-zinc-200">
                Add to Firefox <span aria-hidden="true">→</span>
              </a>
            </p>
          </dd>
        </div>
      </div>

      <!-- System Requirements -->
      <div class="mx-auto mt-32 max-w-2xl sm:mt-40 lg:mt-48 lg:max-w-none animate-fade-in delay-300">
        <div class="mx-auto max-w-2xl lg:text-center">
          <h2 class="text-base font-semibold leading-7 text-zinc-400">Browser Support</h2>
          <p class="mt-2 text-3xl font-bold tracking-tight text-white sm:text-4xl">
            Supported Browsers
          </p>
        </div>
        <div class="mx-auto mt-16 max-w-2xl sm:mt-20 lg:mt-24 lg:max-w-none">
          <dl class="grid max-w-xl grid-cols-1 gap-x-8 gap-y-16 lg:max-w-none lg:grid-cols-2">
            <div class="flex flex-col">
              <dt class="text-base font-semibold leading-7 text-white">Chrome-based Browsers</dt>
              <dd class="mt-4 flex flex-auto flex-col text-base leading-7 text-zinc-300">
                <ul class="list-disc pl-6 space-y-3">
                  <li>Google Chrome</li>
                  <li>Microsoft Edge</li>
                  <li>Brave</li>
                  <li>Opera</li>
                  <li>Other Chromium-based browsers</li>
                </ul>
              </dd>
            </div>
            <div class="flex flex-col">
              <dt class="text-base font-semibold leading-7 text-white">Other Browsers</dt>
              <dd class="mt-4 flex flex-auto flex-col text-base leading-7 text-zinc-300">
                <ul class="list-disc pl-6 space-y-3">
                  <li>Firefox (Supported)</li>
                  <li>Safari (Experimental)</li>
                </ul>
              </dd>
            </div>
          </dl>
        </div>
      </div>

      <!-- Installation Guide -->
      <div class="mx-auto mt-32 max-w-2xl sm:mt-40 lg:mt-48 lg:max-w-none animate-fade-in delay-400">
        <div class="mx-auto max-w-2xl lg:text-center">
          <h2 class="text-base font-semibold leading-7 text-zinc-400">Installation Guide</h2>
          <p class="mt-2 text-3xl font-bold tracking-tight text-white sm:text-4xl">
            How to install BetterSEQTA Plus
          </p>
        </div>
        <div class="mx-auto mt-16 max-w-2xl sm:mt-20 lg:mt-24 lg:max-w-none">
          <dl class="grid max-w-xl grid-cols-1 gap-x-8 gap-y-16 lg:max-w-none lg:grid-cols-3">
            <div class="flex flex-col">
              <dt class="text-base font-semibold leading-7 text-white">Chrome/Edge</dt>
              <dd class="mt-4 flex flex-auto flex-col text-base leading-7 text-zinc-300">
                <ol class="list-decimal pl-6 space-y-3">
                  <li>Click "Add to Chrome/Edge"</li>
                  <li>Confirm the installation</li>
                  <li>Visit SEQTA Learn</li>
                  <li>Enjoy the enhanced experience!</li>
                </ol>
              </dd>
            </div>
            <div class="flex flex-col">
              <dt class="text-base font-semibold leading-7 text-white">Firefox</dt>
              <dd class="mt-4 flex flex-auto flex-col text-base leading-7 text-zinc-300">
                <ol class="list-decimal pl-6 space-y-3">
                  <li>Click "Add to Firefox"</li>
                  <li>Confirm the installation</li>
                  <li>Visit SEQTA Learn</li>
                  <li>Enjoy the enhanced experience!</li>
                </ol>
              </dd>
            </div>
            <div class="flex flex-col">
              <dt class="text-base font-semibold leading-7 text-white">Safari</dt>
              <dd class="mt-4 flex flex-auto flex-col text-base leading-7 text-zinc-300">
                <ol class="list-decimal pl-6 space-y-3">
                  <li>Download from GitHub</li>
                  <li>Enable developer mode</li>
                  <li>Load the extension</li>
                  <li>Visit SEQTA Learn</li>
                </ol>
              </dd>
            </div>
          </dl>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
useHead({
  title: "Download",
});
</script>

<style scoped>
@keyframes fade-in {
  from { opacity: 0; transform: translateY(24px); }
  to { opacity: 1; transform: none; }
}
@keyframes slide-down {
  from { opacity: 0; transform: translateY(-24px); }
  to { opacity: 1; transform: none; }
}
.animate-fade-in {
  animation: fade-in 0.8s cubic-bezier(0.4,0,0.2,1) both;
}
.animate-slide-down {
  animation: slide-down 0.8s cubic-bezier(0.4,0,0.2,1) both;
}
.delay-100 { animation-delay: 0.1s; }
.delay-200 { animation-delay: 0.2s; }
.delay-300 { animation-delay: 0.3s; }
.delay-400 { animation-delay: 0.4s; }
</style>
